# Generated by Django 6.0.7 on 2026-07-31 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='qr_code',
        ),
        migrations.AddField(
    model_name='userprofile',
    name='user',
    field=models.OneToOneField(
        null=True,
        blank=True,
        on_delete=django.db.models.deletion.CASCADE,
        to=settings.AUTH_USER_MODEL
    ),
),
      migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
