# Generated by Django 6.0.7 on 2026-08-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_required',
            field=models.IntegerField(),
        ),
    ]
