# Generated by Django 5.2.16 on 2026-08-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
