# Generated by Django 5.2.16 on 2026-08-05 16:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_bloodrequest_emergency_contact_bloodrequest_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(default=django.utils.timezone.now)),
                ('certificate_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
