# Generated by Django 5.2.16 on 2026-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_donationcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='donation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
