# Generated by Django 5.2.16 on 2026-08-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bloodrequest_donation_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='donation_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='donation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
