# Generated by Django 5.2.16 on 2026-08-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_bloodrequest_donation_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('units_required', models.PositiveIntegerField(default=1)),
                ('hospital_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_type', models.CharField(choices=[('Accident', 'Accident'), ('Surgery', 'Surgery'), ('Emergency', 'Emergency'), ('Other', 'Other')], default='Accident', max_length=50)),
                ('urgency', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('HIGH', 'HIGH'), ('NORMAL', 'NORMAL')], default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('MATCHED', 'MATCHED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_required',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
