# Generated by Django 5.2.16 on 2026-08-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
