# Generated by Django 5.2.16 on 2026-08-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_notification_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
