# Generated by Django 5.2.16 on 2026-08-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_emergencyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyresponse',
            name='emergency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.emergencyrequest'),
        ),
    ]
